spring.application.name=cloud-config-client

#below line property connects server that connects to github
spring.config.import=configserver:http://localhost:8080

server.port=8004
management.endpoints.web.exposure.exclude=*
