spring.application.name=SpringOAuthDemo

spring.security.oauth2.client.registration.google.client-id:548164764131-5pqbvj5km2r7nnvg2i0b88qf9sp1fotl.apps.googleusercontent.com


spring.security.oauth2.client.registration.google.client-secret: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